services:
  # Service for the .NET app
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile located in the current directory
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db  # Ensure db service starts before the app
    networks:
      - my_custom_bridge  # Connect to the custom bridge network

  # Service for Microsoft SQL Server Developer Edition
  db:
    build:
      context: ./db-init  # Build the image using the Dockerfile in the 'db-init' folder
      dockerfile: Dockerfile  # Ensure that this is the correct path to the Dockerfile
    environment:
      - SA_PASSWORD=StrongP@ssw0rd123  # Password must match the connection string
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer  # Developer edition license key
    ports:
      - "1433:1433"  # Expose SQL Server port 1433
    volumes:
      - sql_data:/var/opt/mssql  # Volume for SQL Server data persistence
      - ./db-init:/db-init  # Mount the init scripts folder
    command: /bin/bash -c "/usr/src/app/wait-for-sqlserver.sh && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P StrongP@ssw0rd123 -d master -i /tmp/personadb.ddl"
    networks:
      - my_custom_bridge  # Connect to the custom bridge network

networks:
  my_custom_bridge:  # Define the custom bridge network

volumes:
  sql_data:  # Define the volume for SQL Server data persistence
